### ISSUE TITLE
Dice rolls with modifiers show each die result, but rolls without modifers don't.

### ISSUE THREAD

**Issue by Enochsoul** [ShooterAndy/Dicecord#1]
Playing a game that needed to know the individual die results, and noticed that Dicecord(which we'd been using until this game) only showed individual die results when adding a modifier.

[7:03 PM]  Klaus: -roll 3d6
[7:03 PM]  BOT Dicecord: Klaus, 
3d6  =  15.
[7:04 PM]  Klaus: -roll 3d6+5
[7:04 PM]  BOT Dicecord: Klaus, 
3d6 + 5  =  6 + 6 + 6 + 5  =  23.
7:05 PM]  Klaus: -roll 1d6 +3

**Comment by ShooterAndy** [comment]
This is a known bug that will be fixed in 3.0.0.

**Comment by ShooterAndy** [comment]
Fixed in 3.0.0
