### ISSUE TITLE
Server owner attempting !setprefix results in "Error: Only a guild administrator can change the prefix for this Discord Guild."

### ISSUE THREAD

**Issue by LaurensPlompen** [ShooterAndy/Dicecord#16]
When the server owner attempts to change the bot prefix using the !setprefix command, the bot responds with "Error: Only a guild administrator can change the prefix for this Discord Guild." (note: Guild is the old name for a Discord server). The server owner also has the 'Admin' role.

<img width="520" alt="dicecord bug 1" src="https://user-images.githubusercontent.com/107516964/173703945-d64adcb6-7c1e-4ef3-b5a1-ac9a13e4835d.PNG">
<img width="244" alt="dicecord bug 2" src="https://user-images.githubusercontent.com/107516964/173703991-8088ce92-568f-4700-8267-2896c158ae5a.PNG">

One thing that is particular to this server is that the @\everyone role has no viewing rights to any channels except for a few (this is done to enfore new users to accept the server rules, after which they get a 'Member' role which allows them access to the common channels). However, there are multiple public channels in the main category where Dicecord has access and it has automatically joined. It responds correctly to all !roll, !shuffle, !help etc commands there, as expected with the default prefix. We have tried the !setprefix command in a channel under a custom category, but also in the main category, both attempts done by the server owner and also regular users, but no success.

**Comment by ShooterAndy** [comment]
Hi, @LaurensPlompen!

Thanks for pointing out this issue: I inadvertently broke this while reducing the resource usage of the bot and didn't notice the issue. It should be fixed now, please try again and re-open this issue if it's still broken.

**Comment by LaurensPlompen** [comment]
Brilliantly done @ShooterAndy, it works like a charm! Thanks for the quick solution <3
