### ISSUE TITLE
Using "CountOver" with a formula modifier mistakenly counts "Over and On" the specified value

### ISSUE THREAD

**Issue by bwaller94** [ShooterAndy/Dicecord#17]
I believe there is an issue with the interaction between the [count over] argument and adding formulas to the dice rolls.

When rolling dice with a normal co command, it will correctly only count "over", not "on and over". For example, in the following roll, the co5 count all values 6-10, and does not include 5:
![image](https://user-images.githubusercontent.com/26260181/201399778-a5a044b1-e75b-47b1-82ee-c5a78175999f.png)

But if I add a formula modifier to the roll, co switches from only counting "over" to counting both "over" and "on." In this example, the roll with co5 and a +2 modifier should count all values 4-10, but it instead counts 3-10:
![image](https://user-images.githubusercontent.com/26260181/201400132-9c0a6341-c39f-45e1-8701-6f9c3434da10.png)

**Comment by ShooterAndy** [comment]
Hey, @bwaller94!

I think you misunderstood: the modifier does not apply to the roll, it applies to the result of the count.

In your second screenshot, it counts 8, 7, 8, 6, and 7, so, five in total, and then adds 2 to that 5, resulting in 7, which is what you see.

Does that help?

As an aside, any idea why you don't see the profile picture for the bot?

**Comment by bwaller94** [comment]
Ahhh that makes sense! Thank you for the clarification.

In case I missed it, is there any command that does apply a modifier to the
individual dice rolls? If not, that may be a helpful feature. I am using
the bot for Twilight Imperium, and they are many cases where we are
performing combat rolls and need to apply +X to the value of all rolls. We
can a achieve the same result by simply lowering the CountOver value by
that same amount, but being able to see the added value on the result would
be great.

Thanks again!

**Comment by bwaller94** [comment]
Oh and for the Profile Pic, that is an issue on my end. I took these screenshots while on my work computer, and it fails to load a lot of Discord assets when connected to the office network. The same goes for person profile pics, server images, emoticons, etc.

**Comment by ShooterAndy** [comment]
> In case I missed it, is there any command that does apply a modifier to the individual dice rolls?

Not currently, no, and I'm not exactly sure what the syntax for that would even be, but I'll think about it.

> Oh and for the Profile Pic, that is an issue on my end.

Alright, good to know, thanks!

Closing this issue.
