### ISSUE TITLE
Please add exploding dice

### ISSUE THREAD

**Issue by karohemd** [ShooterAndy/Dicecord#2]
It would be great if exploding dice (roll again if the maximum is reached and add the new roll, e.g. 8 on a d8) could be incorporated.
Thank you very much!

**Comment by ghost** [comment]
sorry, I added another ticket for this same item.  Here's my notes:

This function can't be used in Savage Worlds Adventure Edition which allows any dietype to explode. My players might use a d4 and always keep a running total while explodes on 4's but not possible with dicecord. I'm not a java guru so please bear with me. I may be messing up your parse.

I'd like to see it function similar to the following example:

input:
!r 1d6+2e6 vs 5 ? [Fighting]

output:
[Fighting]: 1d6 vs 5 = 6 + 6 + 6 + 4 + 2 = 24 success!

Thanks for your time.

**Comment by ShooterAndy** [comment]
Yep, I know this is used in quite a few systems, and it's in the plans for version 3.0.0.

**Comment by ShooterAndy** [comment]
Added in version 3.0.0, see the "e" dice modifier in the "Dice modifiers" section here: https://bit.ly/3oM6rap
